:toc: macro
:toc-title:

toc::[]

# Developing Kiali Operator

## Setting up your local git repositories

The Kiali Operator source lives in its link:https://github.com/kiali/kiali-operator[own git repository], but because it is necessary for Kiali developers to use it, the Kiali Operator repository should be accessible in the link:https://github.com/kiali/kiali[Kiali git repo] via a softlink in the "operator" directory or just cloned right inside the "operator" directory.

For example:

```
# Clone Kiali Operator in a local git repository location
cd $HOME/source
git clone git@github.com:kiali/kiali-operator.git

# Go to your existing Kiali local git repository
GOPATH=<your GO path to the Kiali project - something like $HOME/source/kiali>
cd $GOPATH/src/github.com/kiali/kiali

# Provide a link to your Kiali Operator local git repository
ln -s $HOME/source/kiali-operator operator
```

NOTE: If you want to clone directly into your kiali/kiali operator directory, you run something like: `git clone git@github.com:kiali/kiali-operator.git $GOPATH/src/github.com/kiali/kiali/operator`. However, if you plan on making code changes to the operator, it is highly recommended you use the softlink approach mentioned above. See the WARNING below for an explanation for this recommendation.

WARNING: If you git cloned the operator repo directly into your kiali/kiali git repo's `operator/` directory, and you need to checkout an older branch of your kiali git repo, then you must make sure you push any operator changes to your remote fork *before* you checkout that older kiali repo branch, otherwise you will lose those operator changes. This is because the operator directory will get replaced with the old kiali repo branch's original operator content. When you then checkout the master branch again, your operator directory will be deleted. At this point, you will need to either create your softlink again or re-clone the git repo. It is for this reason that it is recommended that the operator directory be a softlink that points to an external directory where you have git cloned the operator repo (with a softlink, your operator code changes remain intact - you merely have to recreate the softlink again).

This now makes it easy for Kiali developers to use the operator when working directly in the Kiali git repo. The Kiali git repo has all the necessary `make` targets to build, deploy, and test the Kiali Operator along with Kiali itself. This is very similiar to how things worked prior to moving the operator code to a separate git repo.

The Kiali Operator git repo itself has a very small link:Makefile[] whose sole job is to build and push the Kiali Operator container image. This Makefile is used mainly for CI and release automation; developers typically will not need to use it.

## Developing Kiali Operator While Working In Kiali Git Repo

Assuming you set up your local git repositories as explained in the above section link:#setting-up-your-local-git-repositories[Setting up your local git repositories], then you can develop Kiali Operator features and bug fixes while working in the local Kiali repo directory.

If, however, a developer needs to make changes to the operator, because the Kiali Operator code really lives in a separate repo, the developer will need to create PRs to the Kiali Operator git repo (just like any other git repo you want to commit to). Simply use the same basic workflow and commands that you are used to using already when creating PRs - just remember you need to create a PR from within the Kiali local repo (if changes were made to it) and you need to create another PR from within the "operator" local repo (if changes were made to the operator code).

## Running the Kiali Operator

### Installing the Operator in a Cluster

The link:https://github.com/kiali/kiali[Kiali git repo] has a link:https://github.com/kiali/kiali/blob/master/Makefile[Makefile] and a set of link:https://github.com/kiali/kiali/blob/master/make[Makefile targets] that are used in conjunction with the Kiali Operator so you can install and run the operator built from your local git clones. They use the Kiali Operator helm chart to install the operator, so you must link:https://github.com/kiali/kiali#building[clone the helm-chart git repo in the proper place as well].

To install the operator that contains your local changes, run `make operator-create`. If you are using minikube, you will need to set the environment variable `CLUSTER_TYPE=minikube` and you need to also set `MINIKUBE_PROFILE` if your minikube profile name is not `minikube`. At this point you can create your own Kiali CR to trigger the operator to install Kiali, or use `make kiali-create` to install a sample Kiali CR for you.

### Running the Operator Playbook Without Installing in a Cluster

Sometimes you made simple changes to the operator playbook and roles that can be quickly tested by running the Ansible playbook on your local machine. This saves time because it doesn't require you to install the operator directly in your cluster. To do this, you must have Ansible installed (e.g. `ansible-playbook` must be in your $PATH). You can run the operator playbook via `make run-operator-playbook`. This will run both the kiali-deploy and kiali-remove playbooks so the operator will install and then immediately uninstall a Kiali Server. The operator playbook is configured via the files found in the link:dev-playbook-config[dev-playbook-config directory].

## The Initial Kiali Operator Git Repo Creation

NOTE: This section documents how the Kiali Operator git repo was originally created. This only had to be performed one time and one time only. Developers and consumers of Kiali and Kiali Operator do not need to know any of this, so you can skip this section. This is here just for historical purposes.

The new Kiali Operator git repo was created with a empty history. Once a repo was created, it then needed to be populated with the original operator code from the Kiali git repo while retaining all history. Here is how this was done:

1. Go to a local git repository of the Kiali repo.
2. Create a new branch to be used to populate the new Kiali Operator git repo: `git checkout -b split-operator-master origin/master`
3. Extract only the operator files retaining all history: `git filter-branch --subdirectory-filter operator`
4. Push the operator files to the Kiali Operator git repo's master branch: `git push --force -u git@github.com:kiali/kiali-operator.git split-operator-master:master`

Analogous steps were done for the other branches `v1.0` and `v1.12`.

The `operator` directory in the Kiali git repository is no longer used - it thus is removed and ignored, leaving room for developers to link in their working copy of their local Kiali Operator git repository.

1. Go to a local git repository of the Kiali repo.
2. Create a branch to create a PR with: `git checkout -b remove-operator origin/master`
3. Delete the `operator` directory and ignore it to get it out of the way permanently: `rm -rf operator && echo operator >> .gitignore`
4. Commit the change: `git commit -am "Remove and ignore the operator directory"`
5. Push and create a PR from this remove-operator branch, then merge the PR to fully remove the operator from master.

# How To Change Resources or Configuration

If you need to alter Kubernetes resources for either the Kiali Server or Operator, or if you need to add, remove, or modify a configuration setting, here are the places you need to check and possibly edit. You must make changes to all of these in order to support the different install mechanisms.

The Operator's own resources are deployed either via OLM or the Operator Helm Chart. You must make changes to support them all. Today there are three sets of OLM metadata maintained in the kiali-operator repository - we call them the "golden copies" because they are the source of truth for the link:https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/kiali[OperatorHub.io upstream operator], link:https://github.com/operator-framework/community-operators/tree/master/community-operators/kiali[community operator], and the Red Hat OSSM Operator. The Operator Helm Chart templates are link:https://github.com/kiali/helm-charts/tree/master/kiali-operator[here.]

The Kiali server resources are deployed by the link:./roles[Kiali Operator Ansible roles] or by the link:https://github.com/kiali/helm-charts/tree/master/kiali-server[Kiali Server Helm Chart]. There are link:./roles/default/kiali-deploy/templates/kubernetes[generic Kubernetes templates] as well as link:./roles/default/kiali-deploy/templates/openshift[OpenShift templates] for the link:./roles/default[default] (i.e. current) release as well as link:./roles[select previous releases]. The custom dashboards templates are cluster-type-agnostic and are link:./roles/default/kiali-deploy/templates/dashboards[here].

The configuration settings for the Kiali CR and Kiali ConfigMap are documented in the link:./deploy/kiali/kiali_cr.yaml[kiali_cr.yaml example file] and are defined in the Kiali Operator Ansible roles and in the Helm Charts, described below in more detail.

The default values for all configuration settings are found in the Kiali Operator link:./roles/default/kiali-deploy/defaults/main.yml[defaults/main.yml file] (there are analogous `defaults/main.yml` files for the select previous releases) and in the link:https://github.com/kiali/helm-charts/tree/master/kiali-operator/values.yaml[Kiali Operator Helm Chart] and link:https://github.com/kiali/helm-charts/tree/master/kiali-server/values.yaml[Kiali Server Helm Chart].

If new Kiali Server resources are added or removed, you must make appropriate changes to the link:./roles/default/kiali-remove[Kiali Operator Remove Role] as well.

## Developer Checklists When Changing Resources or Configuration

Below are checklists that developers should consult when making various kinds of changes.

#### Maintain Backward Compatibility

NOTE: Remember to maintain backward compatiblity for all supported versions. Do **not** make any changes if those changes would break the older supported versions. For example, if you are removing permissions from the operator roles/rolebindings within the golden copies, and if those permissions are required by the older supported versions such as link:./roles/v1.24[`v1.24`], then you must not make those changes. Only when those older versions are no longer supported can you make those changes. In this case, create a github issue as a reminder to make the changes at the appropriate time in the future when those versions are no longer supported.

### Run Molecule Tests

WARNING: This may not work if you have SELinux enabled. If you get permission errors, disable SELinux via `setenforce 0` and try again.

When making any kind of change, you should also make the necessary changes to the link:./molecule/[Molecule tests] to ensure they still pass. You can easily run the Molecule tests on your local box using Minikube by running the link:https://github.com/kiali/kiali/blob/master/hack/ci-minikube-molecule-tests.sh[ci-minikube-molecule-tests.sh] hack script. If you want to run just a few or one Molecule test rather than the whole suite, you can run something like this (omit `CLUSTER_TYPE` if running the test on OpenShift; you can omit `MINIKUBE_PROFILE` if your profile is the default of `minikube`).

```
CLUSTER_TYPE=minikube MINIKUBE_PROFILE=ci MOLECULE_USE_DEV_IMAGES=true MOLECULE_SCENARIO="api-test" make clean build test cluster-push molecule-test
```

where `api-test` is the Molecule test(s) you want to run. The value of link:https://github.com/kiali/kiali/blob/v1.25.0/make/Makefile.molecule.mk#L5-L8[`MOLECULE_SCENARIO`] is a space-separated list of Molecule tests - the full list of Molecule tests are link:./molecule[found here]. There are other environment variables you can set (such as `MOLECULE_DEBUG` for turning on debug messages) - see the link:https://github.com/kiali/kiali/blob/master/make/Makefile.molecule.mk[make/Makefile.molecule.mk] file in the kiali/kiali repo.

NOTE: If you have never run the Molecule tests before, the Molecule container image will be built for you automatically. If you need to rebuild the image for some reason, run `FORCE_MOLECULE_BUILD=true make molecule-build`.

### Are You Altering a Kiali Operator Resource?

- [ ] Update the golden copy of the link:./manifests/kiali-upstream[kiali-upstream CSV metadata] (_* **see link:#maintain-backward-compatibility[note] above**_)
- [ ] Update the golden copy of the link:./manifests/kiali-community[kiali-community CSV metadata] (_* **see link:#maintain-backward-compatibility[note] above**_)
- [ ] Update the golden copy of the link:./manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml[kiali-ossm CSV metadata] (_* **see link:#maintain-backward-compatibility[note] above**_)
- [ ] Update the link:https://github.com/kiali/helm-charts/tree/master/kiali-operator/templates[Operator Helm Chart templates]

### Are You Altering a Kiali Server Resource?

- [ ] Update the link:./roles/default/kiali-deploy/templates/kubernetes[Operator Kubernetes templates]
- [ ] Update the link:./roles/default/kiali-deploy/templates/openshift[Operator OpenShift templates]
- [ ] Check if you need to modify the link:./roles/default/kiali-remove[Operator remove role]
- [ ] Update the link:https://github.com/kiali/helm-charts/tree/master/kiali-server/templates[Server Helm Chart templates]

### Are You Altering a Kiali Server Role Permission?

- [ ] Update the golden copy of the link:./manifests/kiali-upstream[kiali-upstream CSV metadata] (_* **see link:#maintain-backward-compatibility[note] above**_)
- [ ] Update the golden copy of the link:./manifests/kiali-community[kiali-community CSV metadata] (_* **see link:#maintain-backward-compatibility[note] above**_)
- [ ] Update the golden copy of the link:./manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml[kiali-ossm CSV metadata] (_* **see link:#maintain-backward-compatibility[note] above**_)
- [ ] Update the link:./roles/default/kiali-deploy/templates/kubernetes/role.yaml[Operator Kubernetes role.yaml]
- [ ] Update the link:./roles/default/kiali-deploy/templates/kubernetes/role-viewer.yaml[Operator Kubernetes role-viewer.yaml]
- [ ] Update the link:./roles/default/kiali-deploy/templates/openshift/role.yaml[Operator OpenShift role.yaml]
- [ ] Update the link:./roles/default/kiali-deploy/templates/openshift/role-viewer.yaml[Operator OpenShift role-viewer.yaml]
- [ ] Update the link:https://github.com/kiali/helm-charts/tree/master/kiali-operator/templates/clusterrole.yaml[Operator Helm Chart clusterrole.yaml]
- [ ] Update the link:https://github.com/kiali/helm-charts/tree/master/kiali-server/templates/role.yaml[Server Helm Chart role.yaml]
- [ ] Update the link:https://github.com/kiali/helm-charts/tree/master/kiali-server/templates/role-viewer.yaml[Server Helm Chart role-viewer.yaml]

### Are You Altering a Kiali Server Configuration Setting?

- [ ] Set the default value in link:./roles/default/kiali-deploy/defaults/main.yml[Operator default/main.yaml]
- [ ] If adding a new top-level group or setting, add it to link:./roles/default/kiali-deploy/vars/main.yml[Operator vars/main.yaml]
- [ ] Document the new value in the link:./deploy/kiali/kiali_cr.yaml[example kiali_cr.yaml] (put the default values in the comments)
- [ ] Only if appropriate (usually it is not) set the value in the `cr.spec` section of link:https://github.com/kiali/helm-charts/tree/master/kiali-operator/values.yaml[Operator Helm Chart values.yaml]
- [ ] Set the default value in the link:https://github.com/kiali/helm-charts/tree/master/kiali-server/values.yaml[Server Helm Chart values.yaml]
- [ ] Ensure each group of settings are alphabetically sorted in all the files where the new setting was added.
- [ ] If appropriate, add some tests to the link:./molecule/config-values-test/converge.yml[Molecule config-values-test]

### Do You Need To Backport Changes To Support Older Versions?

- [ ] Changes made to the link:./roles/default[`default`] Ansible role should be duplicated to the versioned Ansible role (e.g. link:./roles/v1.24[`v1.24`])
- [ ] Cherry-pick changes you made in the link:./roles/default[`default`] Ansible role and versioned Ansible roles (e.g. link:./roles/v1.24[`v1.24`]) to the appropriate git branch.
