- name: Change Kiali CR with new Kiali CR
  k8s:
    namespace: '{{ cr_namespace }}'
    definition: "{{ new_kiali_cr }}"
  retries: 10
  delay: 5
  register: kiali_cr_patch_result
  until: kiali_cr_patch_result is succeeded
