---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ ossmconsole_vars_remove.deployment.namespace }}"
  name: nginx-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ ossmconsole_vars_remove.deployment.namespace }}"
  name: plugin-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ ossmconsole_vars_remove.deployment.namespace }}"
  name: ossmconsole
---
apiVersion: v1
kind: Service
metadata:
  namespace: "{{ ossmconsole_vars_remove.deployment.namespace }}"
  name: ossmconsole
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: ossmconsole
