- hosts: localhost
  gather_facts: no
  collections:
  - kubernetes.core
  tasks:

  - debug:
      msg: OSSMCONSOLE RECONCILIATION START

  - debug:
      msg: "CR: name={{ ansible_operator_meta.name }}, namespace={{ ansible_operator_meta.namespace }}"

  - name: Playbook start time
    set_fact:
      playbook_time_start: "{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

  - name: Determine the default playbook
    include_vars:
      file: "default-playbook.yml"
      name: default_playbook

  - name: Determine the version that is to be installed
    set_fact:
      version: "{{ version | default(default_playbook.playbook) }}"

  - name: Determine the default supported images for all known versions
    include_vars:
      file: "ossmconsole-default-supported-images.yml"
      name: supported_ossmconsole_images

  - name: Prepare OSSMConsole supported images (RELATED_IMAGE overrides)
    include_tasks: tasks/ossmconsole-supported-images-prep.yml

  - name: Run the version-specific deploy role
    include_role:
      name: "{{ version }}/ossmconsole-deploy"
    when:
    - skip_reconciliation is not defined or skip_reconciliation == False

  - name: Playbook end time
    set_fact:
      playbook_time_end: "{{ '%Y-%m-%d %H:%M:%S' | strftime }}"

  - name: Log reconciliation processing time
    ignore_errors: yes
    debug:
      msg: "Processing time: [{{ (playbook_time_end|to_datetime - playbook_time_start|to_datetime).total_seconds() | int }}] seconds"

  - debug:
      msg: OSSMCONSOLE RECONCILIATION IS DONE.

